(() => {
  'use strict';
  const locales = window.RECRUITMENT_I18N.locales;

  locales.hi = {
    languageTitle: 'अपनी भाषा चुनें', languageSubtitle: 'पूरा आवेदन चुनी गई भाषा में दिखाया जाएगा।', languageSearch: 'भाषा के नाम या कोड से खोजें…',
    trustPrivate: 'पासपोर्ट स्कैन नहीं', trustMobile: 'मोबाइल पर आसान', trustControl: 'भेजने की पुष्टि आप करते हैं',
    recruiterTitle: 'भर्ती प्रतिनिधि चुनें', recruiterSubtitle: 'उस व्यक्ति को चुनें जिसने आपको यह लिंक भेजा है, या जिस भर्ती प्रतिनिधि से आप संपर्क करना चाहते हैं।', recruiterRequired: 'आवेदन भरने से पहले भर्ती प्रतिनिधि चुनना आवश्यक है।', suggested: 'लिंक द्वारा सुझाया गया', selectedRecruiter: 'चुना हुआ भर्ती प्रतिनिधि', changeLanguage: 'भाषा बदलें', changeRecruiter: 'भर्ती प्रतिनिधि बदलें', recruiterEmail: 'तैयार ईमेल इसी व्यक्ति को भेजा जाएगा।',
    stepContactTitle: 'संपर्क विवरण', stepContactSubtitle: 'भर्ती प्रतिनिधि आपसे कैसे संपर्क करे?', stepLocationTitle: 'स्थान और दस्तावेज़', stepLocationSubtitle: 'बताएँ कि आप अभी कहाँ हैं और आपके पास कौन-से दस्तावेज़ हैं।', stepWorkTitle: 'काम की पसंद', stepWorkSubtitle: 'बताएँ कि आप किस प्रकार का काम खोज रहे हैं।', reviewTitle: 'आवेदन जाँचें', reviewSubtitle: 'ईमेल खोलने से पहले विवरण और चुने हुए भर्ती प्रतिनिधि को जाँचें।',
    firstName: 'नाम', lastName: 'उपनाम', phone: 'देश कोड सहित फ़ोन नंबर', phoneHint: 'अंतरराष्ट्रीय प्रारूप उपयोग करें, जैसे +91…, +380…, +998….', messenger: 'पसंदीदा मैसेंजर', email: 'आपका ईमेल (वैकल्पिक)', citizenship: 'नागरिकता', country: 'वर्तमान देश', city: 'शहर', age: 'आयु', inPoland: 'क्या आप अभी पोलैंड में हैं?', documents: 'पोलैंड में रहने या काम करने के दस्तावेज़', job: 'आप किस काम में रुचि रखते हैं?', experience: 'कार्य अनुभव (वैकल्पिक)', experienceHint: 'अपने पिछले काम, जिम्मेदारियों और अवधि का संक्षिप्त वर्णन करें।', start: 'आप काम कब शुरू कर सकते हैं?', shift: 'क्या आप शिफ्ट में काम कर सकते हैं?', housing: 'क्या आपको आवास चाहिए?', source: 'आपको नौकरी के बारे में कहाँ से पता चला?', comment: 'अतिरिक्त टिप्पणी (वैकल्पिक)',
    safety: 'इस फॉर्म में पासपोर्ट स्कैन, PESEL, बैंक विवरण, पासवर्ड या चिकित्सा दस्तावेज़ दर्ज न करें।', consentBefore: 'मैं पुष्टि करता/करती हूँ कि जानकारी सही है, नौकरी के संबंध में संपर्क की अनुमति देता/देती हूँ और मैंने', privacyLink: 'गोपनीयता जानकारी पढ़ी है',
    required: 'आवश्यक फ़ील्ड', invalidPhone: 'कम से कम 7 अंकों वाला सही अंतरराष्ट्रीय फ़ोन नंबर दर्ज करें।', invalidEmail: 'सही ईमेल दर्ज करें या फ़ील्ड खाली छोड़ें।', invalidAge: 'आवेदन केवल 18 वर्ष या उससे अधिक आयु के लोगों के लिए है।', selectOption: 'एक विकल्प चुनें', back: 'वापस', continue: 'आगे', checkApplication: 'आवेदन जाँचें', edit: 'जानकारी बदलें', sendEmail: 'ईमेल खोलें और भेजें', copyApplication: 'आवेदन कॉपी करें', shareApplication: 'आवेदन साझा करें', downloadTxt: 'TXT डाउनलोड करें', newApplication: 'नया आवेदन',
    options: {
      messenger: { whatsapp: 'WhatsApp', viber: 'Viber', telegram: 'Telegram', phone: 'केवल फ़ोन कॉल', other: 'अन्य' }, yesNo: { yes: 'हाँ', no: 'नहीं' },
      documents: { none: 'कोई पोलिश दस्तावेज़ नहीं', visa: 'पोलिश वीज़ा', residence: 'निवास कार्ड / परमिट', pesel: 'PESEL UKR / अस्थायी संरक्षण', other: 'अन्य दस्तावेज़', unknown: 'मुझे नहीं पता' },
      jobs: { greenhouse: 'ग्रीनहाउस का काम', packing: 'छँटाई और पैकिंग', warehouse: 'वेयरहाउस और लॉजिस्टिक्स', production: 'उत्पादन', cleaning: 'सफाई', driver: 'ड्राइवर', technical: 'तकनीकी काम', other: 'अन्य काम' },
      starts: { now: 'तुरंत', d7: '7 दिनों के भीतर', d14: '14 दिनों के भीतर', d30: '30 दिनों के भीतर', later: 'बाद में' }, shifts: { yes: 'हाँ', no: 'नहीं', depends: 'कार्यसूची पर निर्भर' },
      sources: { facebook: 'Facebook', instagram: 'Instagram', tiktok: 'TikTok', telegram: 'Telegram', whatsapp: 'WhatsApp', viber: 'Viber', referral: 'मित्र / सिफारिश', recruiter: 'भर्ती प्रतिनिधि / एजेंसी', other: 'अन्य' }
    }
  };

  locales.bn = {
    languageTitle: 'ভাষা নির্বাচন করুন', languageSubtitle: 'সম্পূর্ণ আবেদনটি নির্বাচিত ভাষায় দেখানো হবে।', languageSearch: 'ভাষার নাম বা কোড দিয়ে খুঁজুন…',
    trustPrivate: 'পাসপোর্ট স্ক্যান নয়', trustMobile: 'ফোনে ব্যবহার সহজ', trustControl: 'পাঠানো আপনি নিশ্চিত করবেন',
    recruiterTitle: 'রিক্রুটার নির্বাচন করুন', recruiterSubtitle: 'যিনি এই লিঙ্ক পাঠিয়েছেন অথবা যার সঙ্গে যোগাযোগ করতে চান, সেই রিক্রুটারকে নির্বাচন করুন।', recruiterRequired: 'আবেদন পূরণের আগে একজন রিক্রুটার নির্বাচন করা আবশ্যক।', suggested: 'লিঙ্কে প্রস্তাবিত', selectedRecruiter: 'নির্বাচিত রিক্রুটার', changeLanguage: 'ভাষা পরিবর্তন', changeRecruiter: 'রিক্রুটার পরিবর্তন', recruiterEmail: 'প্রস্তুত ইমেইলটি এই ব্যক্তির ঠিকানায় যাবে।',
    stepContactTitle: 'যোগাযোগের তথ্য', stepContactSubtitle: 'রিক্রুটার কীভাবে আপনার সঙ্গে যোগাযোগ করবেন?', stepLocationTitle: 'অবস্থান ও নথি', stepLocationSubtitle: 'আপনি বর্তমানে কোথায় আছেন এবং কী নথি আছে তা জানান।', stepWorkTitle: 'কাজের পছন্দ', stepWorkSubtitle: 'আপনি কী ধরনের কাজ খুঁজছেন তা জানান।', reviewTitle: 'আবেদন পরীক্ষা করুন', reviewSubtitle: 'ইমেইল খোলার আগে তথ্য ও নির্বাচিত রিক্রুটার যাচাই করুন।',
    firstName: 'নাম', lastName: 'পদবি', phone: 'দেশের কোডসহ ফোন নম্বর', phoneHint: 'আন্তর্জাতিক ফরম্যাট ব্যবহার করুন, যেমন +880…, +380…, +998….', messenger: 'পছন্দের মেসেঞ্জার', email: 'আপনার ইমেইল (ঐচ্ছিক)', citizenship: 'নাগরিকত্ব', country: 'বর্তমান দেশ', city: 'শহর', age: 'বয়স', inPoland: 'আপনি কি বর্তমানে পোল্যান্ডে আছেন?', documents: 'পোল্যান্ডে থাকা বা কাজের নথি', job: 'কোন ধরনের কাজে আগ্রহী?', experience: 'কাজের অভিজ্ঞতা (ঐচ্ছিক)', experienceHint: 'পূর্বের কাজ, দায়িত্ব ও সময়কাল সংক্ষেপে লিখুন।', start: 'কবে কাজ শুরু করতে পারবেন?', shift: 'শিফটে কাজ করতে পারবেন?', housing: 'থাকার জায়গা প্রয়োজন?', source: 'চাকরির কথা কোথা থেকে জেনেছেন?', comment: 'অতিরিক্ত মন্তব্য (ঐচ্ছিক)',
    safety: 'এই ফর্মে পাসপোর্ট স্ক্যান, PESEL, ব্যাংক তথ্য, পাসওয়ার্ড বা চিকিৎসা নথি দেবেন না।', consentBefore: 'আমি নিশ্চিত করছি যে তথ্য সঠিক, চাকরি সম্পর্কে যোগাযোগে সম্মত এবং', privacyLink: 'গোপনীয়তা তথ্য পড়েছি',
    required: 'আবশ্যক ঘর', invalidPhone: 'কমপক্ষে ৭ সংখ্যার সঠিক আন্তর্জাতিক ফোন নম্বর লিখুন।', invalidEmail: 'সঠিক ইমেইল লিখুন অথবা ঘরটি ফাঁকা রাখুন।', invalidAge: 'আবেদনটি শুধুমাত্র ১৮ বছর বা তার বেশি বয়সীদের জন্য।', selectOption: 'একটি বিকল্প নির্বাচন করুন', back: 'পেছনে', continue: 'চালিয়ে যান', checkApplication: 'আবেদন পরীক্ষা করুন', edit: 'তথ্য পরিবর্তন', sendEmail: 'ইমেইল খুলুন ও পাঠান', copyApplication: 'আবেদন কপি করুন', shareApplication: 'আবেদন শেয়ার করুন', downloadTxt: 'TXT ডাউনলোড', newApplication: 'নতুন আবেদন',
    options: {
      messenger: { whatsapp: 'WhatsApp', viber: 'Viber', telegram: 'Telegram', phone: 'শুধু ফোন কল', other: 'অন্যান্য' }, yesNo: { yes: 'হ্যাঁ', no: 'না' },
      documents: { none: 'পোলিশ নথি নেই', visa: 'পোলিশ ভিসা', residence: 'রেসিডেন্স কার্ড / অনুমতি', pesel: 'PESEL UKR / অস্থায়ী সুরক্ষা', other: 'অন্যান্য নথি', unknown: 'জানি না' },
      jobs: { greenhouse: 'গ্রিনহাউসের কাজ', packing: 'বাছাই ও প্যাকিং', warehouse: 'গুদাম ও লজিস্টিকস', production: 'উৎপাদন', cleaning: 'পরিচ্ছন্নতা', driver: 'ড্রাইভার', technical: 'প্রযুক্তিগত কাজ', other: 'অন্যান্য কাজ' },
      starts: { now: 'অবিলম্বে', d7: '৭ দিনের মধ্যে', d14: '১৪ দিনের মধ্যে', d30: '৩০ দিনের মধ্যে', later: 'পরে' }, shifts: { yes: 'হ্যাঁ', no: 'না', depends: 'সময়সূচির ওপর নির্ভর করে' },
      sources: { facebook: 'Facebook', instagram: 'Instagram', tiktok: 'TikTok', telegram: 'Telegram', whatsapp: 'WhatsApp', viber: 'Viber', referral: 'পরিচিত / সুপারিশ', recruiter: 'রিক্রুটার / এজেন্সি', other: 'অন্যান্য' }
    }
  };

  locales.ne = {
    languageTitle: 'भाषा छान्नुहोस्', languageSubtitle: 'पूरा आवेदन छानिएको भाषामा देखाइनेछ।', languageSearch: 'भाषाको नाम वा कोडबाट खोज्नुहोस्…',
    trustPrivate: 'राहदानी स्क्यान आवश्यक छैन', trustMobile: 'मोबाइलमा सजिलो', trustControl: 'पठाउने पुष्टि तपाईंले गर्नुहुन्छ',
    recruiterTitle: 'भर्तीकर्ता छान्नुहोस्', recruiterSubtitle: 'तपाईंलाई यो लिङ्क पठाउने व्यक्ति वा सम्पर्क गर्न चाहेको भर्तीकर्ता छान्नुहोस्।', recruiterRequired: 'आवेदन भर्नुअघि भर्तीकर्ता छान्नुपर्छ।', suggested: 'लिङ्कले सुझाव दिएको', selectedRecruiter: 'छानिएको भर्तीकर्ता', changeLanguage: 'भाषा बदल्नुहोस्', changeRecruiter: 'भर्तीकर्ता बदल्नुहोस्', recruiterEmail: 'तयार इमेल यही व्यक्तिलाई पठाइनेछ।',
    stepContactTitle: 'सम्पर्क विवरण', stepContactSubtitle: 'भर्तीकर्ताले तपाईंलाई कसरी सम्पर्क गर्न सक्छ?', stepLocationTitle: 'स्थान र कागजात', stepLocationSubtitle: 'अहिले कहाँ हुनुहुन्छ र कुन कागजात छन् बताउनुहोस्।', stepWorkTitle: 'कामको प्राथमिकता', stepWorkSubtitle: 'कस्तो काम खोज्दै हुनुहुन्छ बताउनुहोस्।', reviewTitle: 'आवेदन जाँच्नुहोस्', reviewSubtitle: 'इमेल खोल्नुअघि विवरण र भर्तीकर्ता जाँच्नुहोस्।',
    firstName: 'नाम', lastName: 'थर', phone: 'देश कोडसहित फोन नम्बर', phoneHint: 'अन्तर्राष्ट्रिय ढाँचा प्रयोग गर्नुहोस्, जस्तै +977…, +380…, +998….', messenger: 'रुचाइएको मेसेन्जर', email: 'तपाईंको इमेल (वैकल्पिक)', citizenship: 'नागरिकता', country: 'हालको देश', city: 'सहर', age: 'उमेर', inPoland: 'के तपाईं अहिले पोल्याण्डमा हुनुहुन्छ?', documents: 'पोल्याण्डमा बस्न वा काम गर्नका कागजात', job: 'कस्तो काममा रुचि छ?', experience: 'कामको अनुभव (वैकल्पिक)', experienceHint: 'अघिल्लो काम, जिम्मेवारी र अवधि छोटकरीमा लेख्नुहोस्।', start: 'काम कहिले सुरु गर्न सक्नुहुन्छ?', shift: 'शिफ्टमा काम गर्न सक्नुहुन्छ?', housing: 'बसोबास आवश्यक छ?', source: 'रिक्त पदबारे कहाँबाट थाहा पाउनुभयो?', comment: 'थप टिप्पणी (वैकल्पिक)',
    safety: 'यस फारममा राहदानी स्क्यान, PESEL, बैंक विवरण, पासवर्ड वा स्वास्थ्य कागजात नदिनुहोस्।', consentBefore: 'जानकारी सही भएको पुष्टि गर्छु, रोजगारीबारे सम्पर्क स्वीकार गर्छु र', privacyLink: 'गोपनीयता जानकारी पढेको छु',
    required: 'अनिवार्य क्षेत्र', invalidPhone: 'कम्तीमा ७ अंक भएको सही अन्तर्राष्ट्रिय फोन नम्बर लेख्नुहोस्।', invalidEmail: 'सही इमेल लेख्नुहोस् वा खाली छोड्नुहोस्।', invalidAge: 'आवेदन १८ वर्ष वा माथिका व्यक्तिका लागि मात्र हो।', selectOption: 'विकल्प छान्नुहोस्', back: 'पछाडि', continue: 'जारी राख्नुहोस्', checkApplication: 'आवेदन जाँच्नुहोस्', edit: 'जानकारी बदल्नुहोस्', sendEmail: 'इमेल खोल्नुहोस् र पठाउनुहोस्', copyApplication: 'आवेदन प्रतिलिपि गर्नुहोस्', shareApplication: 'आवेदन साझा गर्नुहोस्', downloadTxt: 'TXT डाउनलोड', newApplication: 'नयाँ आवेदन',
    options: {
      messenger: { whatsapp: 'WhatsApp', viber: 'Viber', telegram: 'Telegram', phone: 'फोन कल मात्र', other: 'अन्य' }, yesNo: { yes: 'हो', no: 'होइन' },
      documents: { none: 'पोलिश कागजात छैन', visa: 'पोलिश भिसा', residence: 'बसोबास कार्ड / अनुमति', pesel: 'PESEL UKR / अस्थायी सुरक्षा', other: 'अन्य कागजात', unknown: 'थाहा छैन' },
      jobs: { greenhouse: 'हरितगृहको काम', packing: 'छनोट र प्याकिङ', warehouse: 'गोदाम र लजिस्टिक्स', production: 'उत्पादन', cleaning: 'सरसफाइ', driver: 'चालक', technical: 'प्राविधिक काम', other: 'अन्य काम' },
      starts: { now: 'तुरुन्त', d7: '७ दिनभित्र', d14: '१४ दिनभित्र', d30: '३० दिनभित्र', later: 'पछि' }, shifts: { yes: 'हो', no: 'होइन', depends: 'तालिकामा निर्भर' },
      sources: { facebook: 'Facebook', instagram: 'Instagram', tiktok: 'TikTok', telegram: 'Telegram', whatsapp: 'WhatsApp', viber: 'Viber', referral: 'चिनेको व्यक्ति / सिफारिस', recruiter: 'भर्तीकर्ता / एजेन्सी', other: 'अन्य' }
    }
  };

  locales.ur = {
    languageTitle: 'اپنی زبان منتخب کریں', languageSubtitle: 'پورا فارم منتخب زبان میں دکھایا جائے گا۔', languageSearch: 'زبان کے نام یا کوڈ سے تلاش کریں…',
    trustPrivate: 'پاسپورٹ اسکین نہیں', trustMobile: 'فون پر آسان', trustControl: 'بھیجنے کی تصدیق آپ کریں گے',
    recruiterTitle: 'ریکروٹر منتخب کریں', recruiterSubtitle: 'اس شخص کو منتخب کریں جس نے آپ کو یہ لنک بھیجا، یا جس ریکروٹر سے آپ رابطہ کرنا چاہتے ہیں۔', recruiterRequired: 'فارم بھرنے سے پہلے ریکروٹر منتخب کرنا ضروری ہے۔', suggested: 'لنک کی طرف سے تجویز کردہ', selectedRecruiter: 'منتخب ریکروٹر', changeLanguage: 'زبان تبدیل کریں', changeRecruiter: 'ریکروٹر تبدیل کریں', recruiterEmail: 'تیار ای میل اسی شخص کو بھیجی جائے گی۔',
    stepContactTitle: 'رابطے کی معلومات', stepContactSubtitle: 'ریکروٹر آپ سے کیسے رابطہ کرے؟', stepLocationTitle: 'مقام اور دستاویزات', stepLocationSubtitle: 'بتائیں کہ آپ اس وقت کہاں ہیں اور آپ کے پاس کون سی دستاویزات ہیں۔', stepWorkTitle: 'کام کی ترجیحات', stepWorkSubtitle: 'بتائیں کہ آپ کس قسم کا کام تلاش کر رہے ہیں۔', reviewTitle: 'درخواست چیک کریں', reviewSubtitle: 'ای میل کھولنے سے پہلے معلومات اور منتخب ریکروٹر کو چیک کریں۔',
    firstName: 'نام', lastName: 'خاندانی نام', phone: 'ملک کے کوڈ کے ساتھ فون نمبر', phoneHint: 'بین الاقوامی فارمیٹ استعمال کریں، مثلاً +92…، +380…، +998…۔', messenger: 'پسندیدہ میسنجر', email: 'آپ کا ای میل (اختیاری)', citizenship: 'شہریت', country: 'موجودہ ملک', city: 'شہر', age: 'عمر', inPoland: 'کیا آپ اس وقت پولینڈ میں ہیں؟', documents: 'پولینڈ میں رہنے یا کام کرنے کی دستاویزات', job: 'آپ کس کام میں دلچسپی رکھتے ہیں؟', experience: 'کام کا تجربہ (اختیاری)', experienceHint: 'اپنی پچھلی ملازمت، ذمہ داریوں اور مدت کا مختصر ذکر کریں۔', start: 'آپ کام کب شروع کر سکتے ہیں؟', shift: 'کیا آپ شفٹوں میں کام کر سکتے ہیں؟', housing: 'کیا آپ کو رہائش چاہیے؟', source: 'آپ کو اس ملازمت کے بارے میں کہاں سے معلوم ہوا؟', comment: 'اضافی تبصرہ (اختیاری)',
    safety: 'اس فارم میں پاسپورٹ اسکین، PESEL، بینک کی تفصیلات، پاس ورڈ یا طبی دستاویزات درج نہ کریں۔', consentBefore: 'میں تصدیق کرتا/کرتی ہوں کہ معلومات درست ہیں، ملازمت کے بارے میں رابطے کی اجازت دیتا/دیتی ہوں اور میں نے', privacyLink: 'رازداری کی معلومات پڑھ لی ہیں',
    required: 'لازمی خانہ', invalidPhone: 'کم از کم 7 ہندسوں والا درست بین الاقوامی فون نمبر درج کریں۔', invalidEmail: 'درست ای میل درج کریں یا خانہ خالی چھوڑیں۔', invalidAge: 'درخواست صرف 18 سال یا اس سے زیادہ عمر والوں کے لیے ہے۔', selectOption: 'ایک آپشن منتخب کریں', back: 'واپس', continue: 'جاری رکھیں', checkApplication: 'درخواست چیک کریں', edit: 'معلومات تبدیل کریں', sendEmail: 'ای میل کھولیں اور بھیجیں', copyApplication: 'درخواست کاپی کریں', shareApplication: 'درخواست شیئر کریں', downloadTxt: 'TXT ڈاؤن لوڈ', newApplication: 'نئی درخواست',
    options: {
      messenger: { whatsapp: 'WhatsApp', viber: 'Viber', telegram: 'Telegram', phone: 'صرف فون کال', other: 'دیگر' }, yesNo: { yes: 'ہاں', no: 'نہیں' },
      documents: { none: 'پولش دستاویزات نہیں ہیں', visa: 'پولش ویزا', residence: 'رہائشی کارڈ / اجازت', pesel: 'PESEL UKR / عارضی تحفظ', other: 'دیگر دستاویز', unknown: 'معلوم نہیں' },
      jobs: { greenhouse: 'گرین ہاؤس کا کام', packing: 'چھانٹی اور پیکنگ', warehouse: 'گودام اور لاجسٹکس', production: 'پیداوار', cleaning: 'صفائی', driver: 'ڈرائیور', technical: 'تکنیکی کام', other: 'دیگر کام' },
      starts: { now: 'فوراً', d7: '7 دن کے اندر', d14: '14 دن کے اندر', d30: '30 دن کے اندر', later: 'بعد میں' }, shifts: { yes: 'ہاں', no: 'نہیں', depends: 'شیڈول پر منحصر' },
      sources: { facebook: 'Facebook', instagram: 'Instagram', tiktok: 'TikTok', telegram: 'Telegram', whatsapp: 'WhatsApp', viber: 'Viber', referral: 'دوست / سفارش', recruiter: 'ریکروٹر / ایجنسی', other: 'دیگر' }
    }
  };

  locales.si = {
    languageTitle: 'භාෂාව තෝරන්න', languageSubtitle: 'සම්පූර්ණ අයදුම්පත තෝරාගත් භාෂාවෙන් පෙන්වනු ඇත.', languageSearch: 'භාෂාවේ නම හෝ කේතය සොයන්න…',
    recruiterTitle: 'බඳවාගැනීමේ නිලධාරියා තෝරන්න', recruiterSubtitle: 'මෙම සබැඳිය එවූ පුද්ගලයා හෝ ඔබ සම්බන්ධ වීමට කැමති නිලධාරියා තෝරන්න.', recruiterRequired: 'අයදුම්පත පිරවීමට පෙර නිලධාරියෙකු තෝරාගත යුතුය.', suggested: 'සබැඳියෙන් යෝජිතයි', selectedRecruiter: 'තෝරාගත් නිලධාරියා', changeLanguage: 'භාෂාව වෙනස් කරන්න', changeRecruiter: 'නිලධාරියා වෙනස් කරන්න', recruiterEmail: 'සූදානම් කළ ඊමේල් පණිවිඩය මෙම පුද්ගලයාට යවනු ඇත.',
    stepContactTitle: 'සම්බන්ධතා විස්තර', stepContactSubtitle: 'නිලධාරියා ඔබව සම්බන්ධ කරගන්නේ කෙසේද?', stepLocationTitle: 'ස්ථානය සහ ලේඛන', stepLocationSubtitle: 'ඔබ දැන් සිටින ස්ථානය සහ ඇති ලේඛන සඳහන් කරන්න.', stepWorkTitle: 'රැකියා කැමැත්ත', stepWorkSubtitle: 'ඔබ සොයන රැකියාව සඳහන් කරන්න.', reviewTitle: 'අයදුම්පත පරීක්ෂා කරන්න', reviewSubtitle: 'ඊමේල් විවෘත කිරීමට පෙර විස්තර සහ නිලධාරියා පරීක්ෂා කරන්න.',
    firstName: 'නම', lastName: 'වාසගම', phone: 'රටේ කේතය සමඟ දුරකථන අංකය', messenger: 'කැමති පණිවිඩ යෙදුම', email: 'ඔබගේ ඊමේල් (විකල්ප)', citizenship: 'පුරවැසිභාවය', country: 'වත්මන් රට', city: 'නගරය', age: 'වයස', inPoland: 'ඔබ දැන් පෝලන්තයේ සිටිනවාද?', documents: 'පෝලන්තයේ සිටීමට හෝ වැඩ කිරීමට ලේඛන', job: 'ඔබට අවශ්‍ය රැකියාව කුමක්ද?', experience: 'රැකියා පළපුරුද්ද (විකල්ප)', start: 'ඔබට වැඩ ආරම්භ කළ හැක්කේ කවදාද?', shift: 'මුර ක්‍රමයට වැඩ කළ හැකිද?', housing: 'නවාතැන් අවශ්‍යද?', source: 'රැකියාව ගැන දැනගත්තේ කොහෙන්ද?', comment: 'අමතර සටහන', safety: 'මෙහි ගමන් බලපත්‍ර පිටපත්, PESEL, බැංකු තොරතුරු, මුරපද හෝ වෛද්‍ය ලේඛන ඇතුළත් නොකරන්න.', consentBefore: 'තොරතුරු නිවැරදි බව තහවුරු කරමි, රැකියාව සම්බන්ධයෙන් සම්බන්ධ වීමට එකඟ වන අතර', privacyLink: 'පෞද්ගලිකත්ව තොරතුරු කියවා ඇත',
    required: 'අනිවාර්ය ක්ෂේත්‍රය', invalidPhone: 'අවම වශයෙන් ඉලක්කම් 7ක් ඇති වලංගු ජාත්‍යන්තර අංකයක් ඇතුළත් කරන්න.', invalidAge: 'අයදුම්පත වයස අවුරුදු 18 හෝ වැඩි අය සඳහා පමණි.', selectOption: 'විකල්පයක් තෝරන්න', back: 'ආපසු', continue: 'ඉදිරියට', checkApplication: 'අයදුම්පත පරීක්ෂා කරන්න', edit: 'විස්තර වෙනස් කරන්න', sendEmail: 'ඊමේල් විවෘත කර යවන්න', copyApplication: 'අයදුම්පත පිටපත් කරන්න', shareApplication: 'අයදුම්පත බෙදාගන්න', downloadTxt: 'TXT බාගන්න', newApplication: 'නව අයදුම්පත',
    options: {
      messenger: { whatsapp: 'WhatsApp', viber: 'Viber', telegram: 'Telegram', phone: 'දුරකථන ඇමතුම් පමණි', other: 'වෙනත්' }, yesNo: { yes: 'ඔව්', no: 'නැහැ' },
      documents: { none: 'පෝලන්ත ලේඛන නැත', visa: 'පෝලන්ත වීසා', residence: 'නේවාසික කාඩ්පත / අවසරය', pesel: 'PESEL UKR / තාවකාලික ආරක්ෂාව', other: 'වෙනත් ලේඛනය', unknown: 'දන්නේ නැහැ' },
      jobs: { greenhouse: 'හරිතාගාර වැඩ', packing: 'වර්ග කිරීම සහ ඇසුරුම් කිරීම', warehouse: 'ගබඩා සහ ලොජිස්ටික්ස්', production: 'නිෂ්පාදනය', cleaning: 'පිරිසිදු කිරීම', driver: 'රියදුරු', technical: 'තාක්ෂණික වැඩ', other: 'වෙනත් වැඩ' },
      starts: { now: 'වහාම', d7: 'දින 7ක් ඇතුළත', d14: 'දින 14ක් ඇතුළත', d30: 'දින 30ක් ඇතුළත', later: 'පසුව' }, shifts: { yes: 'ඔව්', no: 'නැහැ', depends: 'කාලසටහන අනුව' },
      sources: { facebook: 'Facebook', instagram: 'Instagram', tiktok: 'TikTok', telegram: 'Telegram', whatsapp: 'WhatsApp', viber: 'Viber', referral: 'මිතුරෙකු / නිර්දේශය', recruiter: 'බඳවාගැනීමේ නිලධාරියා / ආයතනය', other: 'වෙනත්' }
    }
  };

  locales.fil = {
    languageTitle: 'Piliin ang wika', languageSubtitle: 'Ipapakita ang buong aplikasyon sa napiling wika.', languageSearch: 'Maghanap ayon sa pangalan o code ng wika…',
    trustPrivate: 'Walang passport scan', trustMobile: 'Madaling gamitin sa telepono', trustControl: 'Ikaw ang magkukumpirma ng pagpapadala',
    recruiterTitle: 'Piliin ang recruiter', recruiterSubtitle: 'Piliin ang taong nagpadala sa iyo ng link o ang recruiter na nais mong kausapin.', recruiterRequired: 'Kailangang pumili ng recruiter bago sagutan ang aplikasyon.', suggested: 'Iminungkahi ng link', selectedRecruiter: 'Napiling recruiter', changeLanguage: 'Palitan ang wika', changeRecruiter: 'Palitan ang recruiter', recruiterEmail: 'Ang nakahandang email ay ipapadala sa taong ito.',
    stepContactTitle: 'Impormasyon sa pakikipag-ugnayan', stepContactSubtitle: 'Paano ka makokontak ng recruiter?', stepLocationTitle: 'Lokasyon at mga dokumento', stepLocationSubtitle: 'Sabihin kung nasaan ka ngayon at anong mga dokumento ang mayroon ka.', stepWorkTitle: 'Kagustuhan sa trabaho', stepWorkSubtitle: 'Sabihin kung anong uri ng trabaho ang hinahanap mo.', reviewTitle: 'Suriin ang aplikasyon', reviewSubtitle: 'Suriin ang impormasyon at recruiter bago buksan ang email.',
    firstName: 'Pangalan', lastName: 'Apelyido', phone: 'Numero ng telepono na may country code', phoneHint: 'Gumamit ng international format, halimbawa +63…, +380…, +998….', messenger: 'Gustong messenger', email: 'Iyong email (opsyonal)', citizenship: 'Pagkamamamayan', country: 'Kasalukuyang bansa', city: 'Lungsod', age: 'Edad', inPoland: 'Nasa Poland ka ba ngayon?', documents: 'Mga dokumento para manatili o magtrabaho sa Poland', job: 'Anong trabaho ang interesado ka?', experience: 'Karanasan sa trabaho (opsyonal)', experienceHint: 'Ilarawan nang maikli ang dating trabaho, tungkulin at haba ng panahon.', start: 'Kailan ka maaaring magsimula?', shift: 'Maaari ka bang magtrabaho nang shifting?', housing: 'Kailangan mo ba ng tirahan?', source: 'Saan mo nalaman ang bakante?', comment: 'Karagdagang komento (opsyonal)',
    safety: 'Huwag maglagay ng passport scan, PESEL, bank details, password o medical document sa form na ito.', consentBefore: 'Kinukumpirma kong tama ang impormasyon, pumapayag akong kontakin tungkol sa trabaho at nabasa ko ang', privacyLink: 'impormasyon sa privacy',
    required: 'Kailangang sagutan', invalidPhone: 'Maglagay ng wastong international phone number na may hindi bababa sa 7 digit.', invalidEmail: 'Maglagay ng wastong email o iwanang blangko.', invalidAge: 'Para lamang sa edad 18 pataas ang aplikasyon.', selectOption: 'Pumili ng opsyon', back: 'Bumalik', continue: 'Magpatuloy', checkApplication: 'Suriin ang aplikasyon', edit: 'Baguhin ang impormasyon', sendEmail: 'Buksan ang email at ipadala', copyApplication: 'Kopyahin ang aplikasyon', shareApplication: 'I-share ang aplikasyon', downloadTxt: 'I-download ang TXT', newApplication: 'Bagong aplikasyon',
    options: {
      messenger: { whatsapp: 'WhatsApp', viber: 'Viber', telegram: 'Telegram', phone: 'Tawag sa telepono lamang', other: 'Iba pa' }, yesNo: { yes: 'Oo', no: 'Hindi' },
      documents: { none: 'Walang Polish documents', visa: 'Polish visa', residence: 'Residence card / permit', pesel: 'PESEL UKR / temporary protection', other: 'Ibang dokumento', unknown: 'Hindi ko alam' },
      jobs: { greenhouse: 'Trabaho sa greenhouse', packing: 'Sorting at packing', warehouse: 'Warehouse at logistics', production: 'Production', cleaning: 'Cleaning', driver: 'Driver', technical: 'Technical work', other: 'Ibang trabaho' },
      starts: { now: 'Agad', d7: 'Sa loob ng 7 araw', d14: 'Sa loob ng 14 araw', d30: 'Sa loob ng 30 araw', later: 'Mamaya' }, shifts: { yes: 'Oo', no: 'Hindi', depends: 'Depende sa schedule' },
      sources: { facebook: 'Facebook', instagram: 'Instagram', tiktok: 'TikTok', telegram: 'Telegram', whatsapp: 'WhatsApp', viber: 'Viber', referral: 'Kaibigan / referral', recruiter: 'Recruiter / agency', other: 'Iba pa' }
    }
  };

  locales.id = {
    languageTitle: 'Pilih bahasa', languageSubtitle: 'Seluruh formulir akan ditampilkan dalam bahasa yang dipilih.', languageSearch: 'Cari nama atau kode bahasa…',
    trustPrivate: 'Tanpa scan paspor', trustMobile: 'Nyaman di ponsel', trustControl: 'Anda mengonfirmasi pengiriman',
    recruiterTitle: 'Pilih perekrut', recruiterSubtitle: 'Pilih orang yang mengirim tautan ini atau perekrut yang ingin Anda hubungi.', recruiterRequired: 'Perekrut harus dipilih sebelum mengisi formulir.', suggested: 'Disarankan oleh tautan', selectedRecruiter: 'Perekrut yang dipilih', changeLanguage: 'Ganti bahasa', changeRecruiter: 'Ganti perekrut', recruiterEmail: 'Email yang telah disiapkan akan ditujukan kepada orang ini.',
    stepContactTitle: 'Informasi kontak', stepContactSubtitle: 'Bagaimana perekrut dapat menghubungi Anda?', stepLocationTitle: 'Lokasi dan dokumen', stepLocationSubtitle: 'Sebutkan lokasi Anda sekarang dan dokumen yang dimiliki.', stepWorkTitle: 'Preferensi pekerjaan', stepWorkSubtitle: 'Sebutkan jenis pekerjaan yang Anda cari.', reviewTitle: 'Periksa formulir', reviewSubtitle: 'Periksa data dan perekrut sebelum membuka email.',
    firstName: 'Nama depan', lastName: 'Nama belakang', phone: 'Nomor telepon dengan kode negara', phoneHint: 'Gunakan format internasional, misalnya +62…, +380…, +998….', messenger: 'Aplikasi pesan pilihan', email: 'Email Anda (opsional)', citizenship: 'Kewarganegaraan', country: 'Negara saat ini', city: 'Kota', age: 'Usia', inPoland: 'Apakah Anda sekarang berada di Polandia?', documents: 'Dokumen untuk tinggal atau bekerja di Polandia', job: 'Pekerjaan apa yang Anda minati?', experience: 'Pengalaman kerja (opsional)', experienceHint: 'Jelaskan secara singkat pekerjaan sebelumnya, tugas dan lamanya bekerja.', start: 'Kapan Anda bisa mulai bekerja?', shift: 'Apakah Anda bisa bekerja dengan sistem shift?', housing: 'Apakah Anda membutuhkan tempat tinggal?', source: 'Dari mana Anda mengetahui lowongan ini?', comment: 'Komentar tambahan (opsional)',
    safety: 'Jangan masukkan scan paspor, PESEL, data bank, kata sandi atau dokumen medis dalam formulir ini.', consentBefore: 'Saya menyatakan informasi ini benar, setuju dihubungi mengenai pekerjaan dan telah membaca', privacyLink: 'informasi privasi',
    required: 'Wajib diisi', invalidPhone: 'Masukkan nomor telepon internasional yang benar dengan sedikitnya 7 digit.', invalidEmail: 'Masukkan email yang benar atau kosongkan kolom.', invalidAge: 'Formulir hanya untuk usia 18 tahun ke atas.', selectOption: 'Pilih opsi', back: 'Kembali', continue: 'Lanjutkan', checkApplication: 'Periksa formulir', edit: 'Ubah data', sendEmail: 'Buka email dan kirim', copyApplication: 'Salin formulir', shareApplication: 'Bagikan formulir', downloadTxt: 'Unduh TXT', newApplication: 'Formulir baru',
    options: {
      messenger: { whatsapp: 'WhatsApp', viber: 'Viber', telegram: 'Telegram', phone: 'Panggilan telepon saja', other: 'Lainnya' }, yesNo: { yes: 'Ya', no: 'Tidak' },
      documents: { none: 'Tidak memiliki dokumen Polandia', visa: 'Visa Polandia', residence: 'Kartu / izin tinggal', pesel: 'PESEL UKR / perlindungan sementara', other: 'Dokumen lain', unknown: 'Tidak tahu' },
      jobs: { greenhouse: 'Pekerjaan rumah kaca', packing: 'Penyortiran dan pengepakan', warehouse: 'Gudang dan logistik', production: 'Produksi', cleaning: 'Kebersihan', driver: 'Pengemudi', technical: 'Pekerjaan teknis', other: 'Pekerjaan lain' },
      starts: { now: 'Segera', d7: 'Dalam 7 hari', d14: 'Dalam 14 hari', d30: 'Dalam 30 hari', later: 'Nanti' }, shifts: { yes: 'Ya', no: 'Tidak', depends: 'Tergantung jadwal' },
      sources: { facebook: 'Facebook', instagram: 'Instagram', tiktok: 'TikTok', telegram: 'Telegram', whatsapp: 'WhatsApp', viber: 'Viber', referral: 'Teman / rekomendasi', recruiter: 'Perekrut / agen', other: 'Lainnya' }
    }
  };

  locales.vi = {
    languageTitle: 'Chọn ngôn ngữ', languageSubtitle: 'Toàn bộ đơn đăng ký sẽ hiển thị bằng ngôn ngữ đã chọn.', languageSearch: 'Tìm theo tên hoặc mã ngôn ngữ…',
    trustPrivate: 'Không cần bản quét hộ chiếu', trustMobile: 'Dễ dùng trên điện thoại', trustControl: 'Bạn xác nhận việc gửi',
    recruiterTitle: 'Chọn nhà tuyển dụng', recruiterSubtitle: 'Chọn người đã gửi liên kết này hoặc nhà tuyển dụng mà bạn muốn liên hệ.', recruiterRequired: 'Bạn phải chọn nhà tuyển dụng trước khi điền đơn.', suggested: 'Được liên kết đề xuất', selectedRecruiter: 'Nhà tuyển dụng đã chọn', changeLanguage: 'Đổi ngôn ngữ', changeRecruiter: 'Đổi nhà tuyển dụng', recruiterEmail: 'Email đã chuẩn bị sẽ được gửi tới người này.',
    stepContactTitle: 'Thông tin liên hệ', stepContactSubtitle: 'Nhà tuyển dụng có thể liên hệ với bạn bằng cách nào?', stepLocationTitle: 'Địa điểm và giấy tờ', stepLocationSubtitle: 'Cho biết bạn đang ở đâu và có những giấy tờ nào.', stepWorkTitle: 'Mong muốn công việc', stepWorkSubtitle: 'Cho biết loại công việc bạn đang tìm kiếm.', reviewTitle: 'Kiểm tra đơn đăng ký', reviewSubtitle: 'Kiểm tra thông tin và nhà tuyển dụng trước khi mở email.',
    firstName: 'Tên', lastName: 'Họ', phone: 'Số điện thoại có mã quốc gia', phoneHint: 'Dùng định dạng quốc tế, ví dụ +84…, +380…, +998….', messenger: 'Ứng dụng nhắn tin ưu tiên', email: 'Email của bạn (không bắt buộc)', citizenship: 'Quốc tịch', country: 'Quốc gia hiện tại', city: 'Thành phố', age: 'Tuổi', inPoland: 'Hiện bạn có ở Ba Lan không?', documents: 'Giấy tờ để ở hoặc làm việc tại Ba Lan', job: 'Bạn quan tâm loại công việc nào?', experience: 'Kinh nghiệm làm việc (không bắt buộc)', experienceHint: 'Mô tả ngắn công việc trước đây, nhiệm vụ và thời gian làm.', start: 'Khi nào bạn có thể bắt đầu?', shift: 'Bạn có thể làm theo ca không?', housing: 'Bạn có cần chỗ ở không?', source: 'Bạn biết tin tuyển dụng từ đâu?', comment: 'Ghi chú thêm (không bắt buộc)',
    safety: 'Không nhập bản quét hộ chiếu, PESEL, thông tin ngân hàng, mật khẩu hoặc tài liệu y tế vào biểu mẫu.', consentBefore: 'Tôi xác nhận thông tin là đúng, đồng ý được liên hệ về việc làm và đã đọc', privacyLink: 'thông tin quyền riêng tư',
    required: 'Trường bắt buộc', invalidPhone: 'Nhập số điện thoại quốc tế hợp lệ có ít nhất 7 chữ số.', invalidEmail: 'Nhập email hợp lệ hoặc để trống.', invalidAge: 'Đơn chỉ dành cho người từ 18 tuổi trở lên.', selectOption: 'Chọn một mục', back: 'Quay lại', continue: 'Tiếp tục', checkApplication: 'Kiểm tra đơn', edit: 'Sửa thông tin', sendEmail: 'Mở email và gửi', copyApplication: 'Sao chép đơn', shareApplication: 'Chia sẻ đơn', downloadTxt: 'Tải TXT', newApplication: 'Đơn mới',
    options: {
      messenger: { whatsapp: 'WhatsApp', viber: 'Viber', telegram: 'Telegram', phone: 'Chỉ gọi điện thoại', other: 'Khác' }, yesNo: { yes: 'Có', no: 'Không' },
      documents: { none: 'Không có giấy tờ Ba Lan', visa: 'Thị thực Ba Lan', residence: 'Thẻ / giấy phép cư trú', pesel: 'PESEL UKR / bảo vệ tạm thời', other: 'Giấy tờ khác', unknown: 'Không biết' },
      jobs: { greenhouse: 'Làm việc trong nhà kính', packing: 'Phân loại và đóng gói', warehouse: 'Kho và hậu cần', production: 'Sản xuất', cleaning: 'Vệ sinh', driver: 'Lái xe', technical: 'Công việc kỹ thuật', other: 'Công việc khác' },
      starts: { now: 'Ngay lập tức', d7: 'Trong 7 ngày', d14: 'Trong 14 ngày', d30: 'Trong 30 ngày', later: 'Muộn hơn' }, shifts: { yes: 'Có', no: 'Không', depends: 'Tùy lịch làm việc' },
      sources: { facebook: 'Facebook', instagram: 'Instagram', tiktok: 'TikTok', telegram: 'Telegram', whatsapp: 'WhatsApp', viber: 'Viber', referral: 'Bạn bè / giới thiệu', recruiter: 'Nhà tuyển dụng / công ty', other: 'Khác' }
    }
  };
})();
