(()=>{'use strict';
const A=document.getElementById('pdfApp');if(!A)return;
const L={pl:['🇵🇱','Polski'],uk:['🇺🇦','Українська'],ru:['🇷🇺','Русский'],en:['🇬🇧','English'],ka:['🇬🇪','ქართული'],az:['🇦🇿','Azərbaycan'],hy:['🇦🇲','Հայերեն'],tr:['🇹🇷','Türkçe'],uz:['🇺🇿','O‘zbekcha']};
const B={brand:'PDF generator',back:'Application',title:'Create PDF',lead:'Enter basic data, add document photos if needed, then choose Print / Save as PDF.',private:'Everything stays on this device. Nothing is uploaded or sent.',language:'Language',documentTitle:'PDF title',name:'First and last name',phone:'Phone',email:'Email (optional)',citizenship:'Citizenship',location:'Location',job:'Position / work',note:'Notes (optional)',photos:'Document photos (optional)',photosHint:'Choose clear JPG, PNG or WEBP images. Each image becomes a separate PDF page.',addPhotos:'Add photos',create:'Create / save PDF',clear:'Clear',saveHint:'In the print window choose “Save as PDF”.',preview:'PDF preview',pages:'pages',summary:'Candidate information',generated:'Generated locally',remove:'Remove',empty:'Enter data or add photos to see the preview.',defaultTitle:'Candidate documents'};
const T={
pl:{brand:'Generator PDF',back:'Ankieta',title:'Utwórz PDF',lead:'Wpisz podstawowe dane, opcjonalnie dodaj zdjęcia dokumentów, a następnie wybierz Drukuj / Zapisz jako PDF.',private:'Wszystko pozostaje na tym urządzeniu. Nic nie jest wysyłane na serwer.',language:'Język',documentTitle:'Tytuł PDF',name:'Imię i nazwisko',phone:'Telefon',email:'E-mail (opcjonalnie)',citizenship:'Obywatelstwo',location:'Lokalizacja',job:'Stanowisko / praca',note:'Uwagi (opcjonalnie)',photos:'Zdjęcia dokumentów (opcjonalnie)',photosHint:'Wybierz czytelne obrazy JPG, PNG lub WEBP. Każdy obraz będzie osobną stroną PDF.',addPhotos:'Dodaj zdjęcia',create:'Utwórz / zapisz PDF',clear:'Wyczyść',saveHint:'W oknie drukowania wybierz „Zapisz jako PDF”.',preview:'Podgląd PDF',pages:'stron',summary:'Dane kandydata',generated:'Utworzono lokalnie',remove:'Usuń',empty:'Wpisz dane lub dodaj zdjęcia.',defaultTitle:'Dokumenty kandydata'},
ru:{brand:'Генератор PDF',back:'Анкета',title:'Создать PDF',lead:'Введите данные, при необходимости добавьте фото документов, затем выберите «Печать / Сохранить как PDF».',private:'Всё остаётся на этом устройстве. Ничего не загружается на сервер.',language:'Язык',documentTitle:'Название PDF',name:'Имя и фамилия',phone:'Телефон',email:'Email (необязательно)',citizenship:'Гражданство',location:'Локация',job:'Должность / работа',note:'Примечание',photos:'Фото документов (необязательно)',photosHint:'Выберите чёткие JPG, PNG или WEBP. Каждое изображение станет отдельной страницей PDF.',addPhotos:'Добавить фото',create:'Создать / сохранить PDF',clear:'Очистить',saveHint:'В окне печати выберите «Сохранить как PDF».',preview:'Предпросмотр PDF',pages:'страниц',summary:'Данные кандидата',generated:'Создано на устройстве',remove:'Удалить',empty:'Введите данные или добавьте фото.',defaultTitle:'Документы кандидата'},
uk:{brand:'Генератор PDF',back:'Анкета',title:'Створити PDF',lead:'Введіть дані, за потреби додайте фото документів, потім виберіть «Друк / Зберегти як PDF».',private:'Усе залишається на цьому пристрої. Нічого не завантажується на сервер.',language:'Мова',documentTitle:'Назва PDF',name:'Ім’я та прізвище',phone:'Телефон',email:'Email (необов’язково)',citizenship:'Громадянство',location:'Локація',job:'Посада / робота',note:'Примітка',photos:'Фото документів (необов’язково)',photosHint:'Оберіть чіткі JPG, PNG або WEBP. Кожне зображення стане окремою сторінкою PDF.',addPhotos:'Додати фото',create:'Створити / зберегти PDF',clear:'Очистити',saveHint:'У вікні друку виберіть «Зберегти як PDF».',preview:'Перегляд PDF',pages:'сторінок',summary:'Дані кандидата',generated:'Створено на пристрої',remove:'Видалити',empty:'Введіть дані або додайте фото.',defaultTitle:'Документи кандидата'},
ka:{brand:'PDF გენერატორი',back:'განაცხადი',title:'PDF-ის შექმნა',lead:'შეიყვანეთ მონაცემები, დაამატეთ ფოტოები და შეინახეთ PDF-ად.',private:'ყველაფერი რჩება ამ მოწყობილობაზე.',language:'ენა',name:'სახელი და გვარი',phone:'ტელეფონი',citizenship:'მოქალაქეობა',location:'ადგილმდებარეობა',job:'სამუშაო',note:'შენიშვნა',photos:'დოკუმენტების ფოტოები',addPhotos:'ფოტოების დამატება',create:'PDF-ის შენახვა',clear:'გასუფთავება',preview:'PDF გადახედვა',defaultTitle:'კანდიდატის დოკუმენტები'},
az:{brand:'PDF generatoru',back:'Ərizə',title:'PDF yaradın',lead:'Məlumatları daxil edin, şəkilləri əlavə edin və PDF kimi saxlayın.',private:'Hər şey bu cihazda qalır.',language:'Dil',name:'Ad və soyad',phone:'Telefon',citizenship:'Vətəndaşlıq',location:'Yer',job:'İş',note:'Qeyd',photos:'Sənəd şəkilləri',addPhotos:'Şəkil əlavə et',create:'PDF saxla',clear:'Təmizlə',preview:'PDF önbaxış',defaultTitle:'Namizəd sənədləri'},
hy:{brand:'PDF գեներատոր',back:'Հայտ',title:'Ստեղծել PDF',lead:'Մուտքագրեք տվյալները, ավելացրեք լուսանկարներ և պահեք PDF։',private:'Ամեն ինչ մնում է այս սարքում։',language:'Լեզու',name:'Անուն և ազգանուն',phone:'Հեռախոս',citizenship:'Քաղաքացիություն',location:'Վայր',job:'Աշխատանք',note:'Նշում',photos:'Փաստաթղթերի լուսանկարներ',addPhotos:'Ավելացնել',create:'Պահել PDF',clear:'Մաքրել',preview:'PDF նախադիտում',defaultTitle:'Թեկնածուի փաստաթղթեր'},
tr:{brand:'PDF oluşturucu',back:'Başvuru',title:'PDF oluştur',lead:'Bilgileri girin, fotoğrafları ekleyin ve PDF olarak kaydedin.',private:'Her şey bu cihazda kalır.',language:'Dil',name:'Ad ve soyad',phone:'Telefon',citizenship:'Vatandaşlık',location:'Konum',job:'İş',note:'Not',photos:'Belge fotoğrafları',addPhotos:'Fotoğraf ekle',create:'PDF kaydet',clear:'Temizle',preview:'PDF önizleme',defaultTitle:'Aday belgeleri'},
uz:{brand:'PDF generator',back:'Ariza',title:'PDF yaratish',lead:'Ma’lumotlarni kiriting, rasmlarni qo‘shing va PDF sifatida saqlang.',private:'Hammasi shu qurilmada qoladi.',language:'Til',name:'Ism va familiya',phone:'Telefon',citizenship:'Fuqarolik',location:'Joylashuv',job:'Ish',note:'Izoh',photos:'Hujjat rasmlari',addPhotos:'Rasm qo‘shish',create:'PDF saqlash',clear:'Tozalash',preview:'PDF ko‘rinishi',defaultTitle:'Nomzod hujjatlari'}};
const S={language:new URL(location.href).searchParams.get('lang')||localStorage.getItem('citronex_pdf_language')||'pl',data:{title:'',name:'',phone:'',email:'',citizenship:'',location:'',job:'',note:''},files:[]};if(!L[S.language])S.language='en';
const t=k=>({...B,...(T[S.language]||{})})[k]||k,e=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'),a=e,bytes=n=>n<1048576?`${Math.ceil(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`;
function render(){document.documentElement.lang=S.language;document.getElementById('brandSubtitle').textContent=t('brand');document.getElementById('backLink').textContent=`← ${t('back')}`;document.getElementById('footerText').textContent=t('private');document.title=`${t('brand')} — Citronex`;
const rows=[[t('name'),S.data.name],[t('phone'),S.data.phone],[t('email'),S.data.email],[t('citizenship'),S.data.citizenship],[t('location'),S.data.location],[t('job'),S.data.job]].filter(([,v])=>String(v).trim()),title=S.data.title||t('defaultTitle'),count=1+S.files.length;
A.innerHTML=`<div class="generator-grid"><section class="panel controls no-print"><span class="eyebrow">PDF · LOCAL ONLY</span><h1>${e(t('title'))}</h1><p class="lead">${e(t('lead'))}</p><div class="privacy-note">🔒 ${e(t('private'))}</div><div class="field"><label for="language">${e(t('language'))}</label><select id="language">${Object.entries(L).map(([c,[f,n]])=>`<option value="${c}" ${c===S.language?'selected':''}>${f} ${e(n)}</option>`).join('')}</select></div>${field('title','documentTitle')}${field('name','name')}<div class="field-grid">${field('phone','phone','tel')}${field('email','email','email')}</div><div class="field-grid">${field('citizenship','citizenship')}${field('location','location')}</div>${field('job','job')}<div class="field"><label>${e(t('note'))}</label><textarea data-field="note">${e(S.data.note)}</textarea></div><div class="field"><label>${e(t('photos'))}</label><div class="upload-box"><input id="photos" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple><strong>＋ ${e(t('addPhotos'))}</strong><small>${e(t('photosHint'))}</small></div><div class="file-list">${S.files.map((x,i)=>`<div class="file-row"><img src="${a(x.url)}" alt=""><span><strong>${e(x.file.name)}</strong><small>${bytes(x.file.size)}</small></span><button class="remove-file" data-remove="${i}" type="button">×</button></div>`).join('')}</div></div><div class="actions"><button id="printButton" class="button primary" type="button">${e(t('create'))}</button><button id="clearButton" class="button secondary" type="button">${e(t('clear'))}</button></div><p class="help">${e(t('saveHint'))}</p></section><section class="panel preview-panel"><div class="preview-title no-print"><span>${e(t('preview'))}</span><span class="page-count">${count} ${e(t('pages'))}</span></div><div class="pdf-pages"><article class="pdf-sheet pdf-cover"><div class="pdf-brand"><img src="../../assets/citronex-logo.jpg" alt="Citronex"><span>${e(t('summary'))}</span></div><h2 class="pdf-title">${e(title)}</h2>${rows.length?`<dl class="pdf-data">${rows.map(([l,v])=>`<dt>${e(l)}</dt><dd>${e(v)}</dd>`).join('')}</dl>`:`<div class="empty-preview">${e(t('empty'))}</div>`}${S.data.note?`<div class="pdf-note">${e(S.data.note)}</div>`:''}<div class="pdf-footer"><span>Citronex / PPO Siechnice</span><span>${e(t('generated'))}</span></div></article>${S.files.map(x=>`<article class="pdf-sheet photo-sheet"><img src="${a(x.url)}" alt="${a(x.file.name)}"></article>`).join('')}</div></section></div>`;bind();}
function field(id,key,type='text'){return`<div class="field"><label for="${id}">${e(t(key))}</label><input id="${id}" data-field="${id}" type="${type}" value="${a(S.data[id])}"></div>`}
function bind(){document.getElementById('language').onchange=x=>{S.language=x.target.value;localStorage.setItem('citronex_pdf_language',S.language);render()};A.querySelectorAll('[data-field]').forEach(x=>x.oninput=()=>{S.data[x.dataset.field]=x.value});document.getElementById('photos').onchange=x=>{[...x.target.files].forEach(f=>{if(f.type.startsWith('image/')&&f.size<=20*1048576)S.files.push({file:f,url:URL.createObjectURL(f)})});render()};A.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{const [y]=S.files.splice(+x.dataset.remove,1);if(y)URL.revokeObjectURL(y.url);render()});document.getElementById('printButton').onclick=()=>window.print();document.getElementById('clearButton').onclick=()=>{S.files.forEach(x=>URL.revokeObjectURL(x.url));S.files=[];Object.keys(S.data).forEach(k=>S.data[k]='');render()}}
render();})();
